### ISSUE TITLE
Table of Contents not updating

### ISSUE THREAD

**Issue by sscoconutree** [Syslifters/HackTheBox-Reporting#3]
Was this an issue? I have created a new project with the default HTB reporting designs but it appears the Table of Contents is not showing the pages? Was there any configuration that I need to do in order to make this work?

![image](https://github.com/Syslifters/HackTheBox-Reporting/assets/59388557/5d292361-6855-4d99-987f-cb9fe226f58e)

**Comment by cmahrl** [comment]
I cannot reproduce this.
According to your screenshot it appears that you have customized the design. Did you delete something from the TOC section in the designer?

I suggest you change the design back to the CDSA standard design. To do this, go to Project settings > Design and select HTB CDSA Report v1.0 again to work away from this basis.

![image](https://github.com/Syslifters/HackTheBox-Reporting/assets/7896159/fb5637fd-21d2-4344-94c8-ea9ce8e7e894)

In the design selection, you can also switch back to your customized design later if you want to apply changes.

![image](https://github.com/Syslifters/HackTheBox-Reporting/assets/7896159/8c750a20-f2f1-410a-a26b-b05689aab7bd)

**Comment by sscoconutree** [comment]
Greetings,

I actually followed the article below when adding the assets related to HTB designs. I haven't changed anything at all and everything is fresh out of the box:

https://www.hackthebox.com/blog/certification-templates

I have checked the Designs tab and it seems the Table of Contents is missing on that part too.

![image](https://github.com/Syslifters/HackTheBox-Reporting/assets/59388557/d2afb13b-ba86-4c00-ad2d-5a8d76c590c0)

**Comment by sscoconutree** [comment]
The CPTS Report has a missing Table of Contents as well. By the way, I reinstalled Sysreptor and imported the HTB report assets and still the same

![image](https://github.com/Syslifters/HackTheBox-Reporting/assets/59388557/100b84eb-a704-4bed-8f94-86df19a91cd6)

**Comment by cmahrl** [comment]
Ok, i can confirm now! Thanks for reporting.

The provided htb-designs.tar.gz contains outdated designs, we'll update them asap. As a workaround for now, change the TOC sections in your imported designs as follows:

from this:
![image](https://github.com/Syslifters/HackTheBox-Reporting/assets/7896159/7ca4d84e-1459-4d91-b165-f8b00d26bbf0)

to this:
![image](https://github.com/Syslifters/HackTheBox-Reporting/assets/7896159/4daa52ef-04bd-4473-8132-198a61b208a3)

Then it should work!

**Comment by sscoconutree** [comment]
Thank you this worked!

**Comment by cmahrl** [comment]
We reverted the documentation to use the old `v-slot` syntax in [841e713](https://github.com/Syslifters/sysreptor/commit/841e7139814bed13d8bcba5d4206aa0157c64973) 

The new `v-slot` data passing in the next release will be compatible with the old and new `v-slot` syntax, such that it does not break existing designs after updating.
